name: Update manifest.json

on:
  schedule:
    - cron: '0 1 * * *'   # Codziennie o 1:00 w nocy UTC
  workflow_dispatch:

jobs:
  update-manifest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Fetch latest ESP32 Marauder release asset
        id: fetch_asset
        run: |
          curl -s https://api.github.com/repos/justcallmekoko/ESP32Marauder/releases \
          | jq -r '[.[] | .assets[] | select(.name | endswith("_2usb.bin"))][0]' > latest_asset.json

      - name: Build manifest.json
        run: |
          NAME=$(jq -r .name latest_asset.json)
          URL=$(jq -r .browser_download_url latest_asset.json)
          VERSION=$(echo "$NAME" | grep -oP 'v\d+_\d+_\d+' | sed 's/_/./g')

          echo "Tworzenie manifest.json dla: $NAME ($VERSION)"

          cat <<EOF > manifest.json
{
  "name": "ESP32 Marauder Firmware",
  "version": "${VERSION}",
  "builds": [
    {
      "chipFamily": "ESP32",
      "parts": [
        { "path": "esp32_marauder.ino.bootloader.bin", "offset": 4096 },
        { "path": "esp32_marauder.ino.partitions.bin", "offset": 32768 },
        { "path": "boot_app0.bin", "offset": 57344 },
        { "path": "${URL}", "offset": 65536 }
      ]
    }
  ]
}
EOF

      - name: Commit and Push manifest
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "🔄 Auto-update manifest.json from justcallmekoko/ESP32Marauder"
          file_pattern: "manifest.json"
